# Generated by Django 6.0 on 2026-04-28 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_role_score_studentprojectscore'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentprojectscore',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentprojectscore',
            name='graded_by',
        ),
        migrations.RemoveField(
            model_name='studentprojectscore',
            name='group',
        ),
        migrations.RemoveField(
            model_name='studentprojectscore',
            name='student',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='StudentProjectScore',
        ),
    ]
